import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import toast from 'react-hot-toast';
import {
  Brain,
  RefreshCw,
  MessageCircle,
  Copy,
  Clock3,
  Sparkles,
  ShieldCheck,
} from 'lucide-react';
import { automationLinkedin, strategy as strategyApi } from '../utils/api';
import { useAccount } from '../contexts/AccountContext';

const formatDateTime = (value) => {
  if (!value) return 'Not available';
  const parsed = new Date(value);
  if (Number.isNaN(parsed.getTime())) return 'Not available';
  return parsed.toLocaleString();
};

const toShortText = (value = '', max = 320) => {
  const normalized = String(value || '').replace(/\s+/g, ' ').trim();
  if (!normalized) return '';
  return normalized.slice(0, max);
};

const parseSummary = (run) => (
  run?.summary && typeof run.summary === 'object' ? run.summary : {}
);

const parseStrategies = (payload) => (
  Array.isArray(payload?.data) ? payload.data : []
);

const parseInboxComments = (payload) => (
  Array.isArray(payload?.comments) ? payload.comments : []
);

const parseWarnings = (payload) => (
  Array.isArray(payload?.warnings) ? payload.warnings : []
);

const parseSuggestionList = (result) => (
  Array.isArray(result?.suggestions) ? result.suggestions : []
);

const AUTO_DRAFT_LIMIT = 12;
const AUTO_DRAFT_CONCURRENCY = 3;

export default function EngagementAssistant() {
  const { selectedAccount, getCurrentAccountId } = useAccount();

  const [strategyOptions, setStrategyOptions] = useState([]);
  const [loading, setLoading] = useState(true);

  const [showAdaptiveTools, setShowAdaptiveTools] = useState(false);
  const [adaptiveRun, setAdaptiveRun] = useState(null);
  const [runningAdaptive, setRunningAdaptive] = useState(false);
  const [includeContextRefresh, setIncludeContextRefresh] = useState(true);

  const [selectedStrategyId, setSelectedStrategyId] = useState('');
  const [statusFilter, setStatusFilter] = useState('unreplied');
  const [inboxComments, setInboxComments] = useState([]);
  const [inboxWarnings, setInboxWarnings] = useState([]);
  const [inboxLoading, setInboxLoading] = useState(false);

  const [expandedCommentId, setExpandedCommentId] = useState('');
  const [generatedByComment, setGeneratedByComment] = useState({});
  const [replyDraftByComment, setReplyDraftByComment] = useState({});
  const [aiLoadingByComment, setAiLoadingByComment] = useState({});
  const [sendingByComment, setSendingByComment] = useState({});
  const [autoDraftProgress, setAutoDraftProgress] = useState({ running: false, completed: 0, total: 0 });

  const generatedByCommentRef = useRef({});
  const replyDraftByCommentRef = useRef({});
  const autoDraftRunIdRef = useRef(0);
  const autoDraftRunningRef = useRef(false);

  useEffect(() => {
    generatedByCommentRef.current = generatedByComment;
  }, [generatedByComment]);

  useEffect(() => {
    replyDraftByCommentRef.current = replyDraftByComment;
  }, [replyDraftByComment]);

  const strategyMap = useMemo(() => {
    const map = new Map();
    for (const item of strategyOptions) {
      map.set(String(item.id), item);
    }
    return map;
  }, [strategyOptions]);

  const selectedStrategyLabel = selectedStrategyId
    ? toShortText(strategyMap.get(String(selectedStrategyId))?.niche || 'Untitled strategy', 60)
    : '';

  const selectedAccountId = getCurrentAccountId?.() || null;
  const selectedAccountType = selectedAccountId && selectedAccount?.isTeamAccount
    ? 'team'
    : (selectedAccountId && selectedAccount?.account_type ? selectedAccount.account_type : null);

  const loadAdaptiveLatest = useCallback(async () => {
    const response = await automationLinkedin.getLatestAdaptiveVaultLoop();
    setAdaptiveRun(response?.data?.run || null);
  }, []);

  const loadCommentInbox = useCallback(async ({ silent = false } = {}) => {
    if (!silent) setInboxLoading(true);
    try {
      const params = {
        limit: 80,
        post_limit: 20,
        per_post_limit: 10,
      };
      if (selectedAccountId) params.account_id = selectedAccountId;
      if (selectedAccountType) params.account_type = selectedAccountType;

      const response = await automationLinkedin.getCommentReplyInbox(params);
      const comments = parseInboxComments(response?.data);
      const warnings = parseWarnings(response?.data);
      setInboxComments(comments);
      setInboxWarnings(warnings);
      setExpandedCommentId((current) => (
        comments.some((item) => String(item.id) === String(current)) ? current : ''
      ));
      void autoGenerateDraftsForComments(comments);
    } catch (error) {
      if (!silent) {
        toast.error(error?.response?.data?.error || 'Failed to load comment inbox');
        setInboxComments([]);
        setInboxWarnings([]);
        setExpandedCommentId('');
      } else {
        console.warn('[EngagementAssistant] silent inbox refresh failed', error?.message || error);
      }
    } finally {
      if (!silent) setInboxLoading(false);
    }
  }, [selectedAccountId, selectedAccountType, selectedStrategyId]);

  const loadInitial = useCallback(async () => {
    try {
      setLoading(true);
      try {
        const strategyResponse = await strategyApi.list();
        setStrategyOptions(parseStrategies(strategyResponse));
      } catch {
        setStrategyOptions([]);
      }
      await Promise.all([loadAdaptiveLatest(), loadCommentInbox({ silent: false })]);
    } catch (error) {
      toast.error(error?.response?.data?.error || 'Failed to load engagement tools');
    } finally {
      setLoading(false);
    }
  }, [loadAdaptiveLatest, loadCommentInbox]);

  useEffect(() => {
    loadInitial();
  }, [loadInitial]);

  useEffect(() => {
    const interval = window.setInterval(() => {
      void loadCommentInbox({ silent: true });
    }, 45000);
    return () => {
      window.clearInterval(interval);
    };
  }, [loadCommentInbox]);

  const handleAdaptiveRun = async () => {
    try {
      setRunningAdaptive(true);
      const payload = {};
      if (selectedAccountId) payload.account_id = selectedAccountId;
      if (selectedAccountType) payload.account_type = selectedAccountType;
      payload.includeContextRefresh = includeContextRefresh;
      payload.reason = 'manual_run_from_engagement_ui';

      const response = await automationLinkedin.runAdaptiveVaultLoop(payload);
      setAdaptiveRun(response?.data?.run || null);
      toast.success('Adaptive vault loop completed');
    } catch (error) {
      toast.error(error?.response?.data?.error || 'Failed to run adaptive vault loop');
    } finally {
      setRunningAdaptive(false);
    }
  };

  const handleCopyReply = async (value) => {
    const text = String(value || '').trim();
    if (!text) return;
    try {
      await navigator.clipboard.writeText(text);
      toast.success('Reply copied');
    } catch {
      toast.error('Copy failed');
    }
  };

  const primeDraftFromSuggestions = useCallback((commentId, suggestions = [], { overwrite = false } = {}) => {
    const firstReply = toShortText(suggestions?.[0]?.reply || '', 1200);
    if (!firstReply) return;
    setReplyDraftByComment((current) => {
      const existing = toShortText(current?.[commentId] || '', 1200);
      if (!overwrite && existing) return current;
      return {
        ...current,
        [commentId]: firstReply,
      };
    });
  }, []);

  const generateForSingleComment = useCallback(async (comment) => {
    const response = await automationLinkedin.generateCommentReply({
      strategyId: selectedStrategyId || undefined,
      postId: comment?.postId || undefined,
      sourceCommentId: comment?.sourceCommentId || undefined,
      commentText: comment?.commentText || '',
      commenterName: comment?.commenterName || '',
      tone: 'professional',
      objective: 'engage',
      suggestionCount: 3,
    });

    const result = response?.data || {};
    setGeneratedByComment((current) => ({
      ...current,
      [String(comment.id)]: result,
    }));
    return result;
  }, [selectedStrategyId]);

  const autoGenerateDraftsForComments = useCallback(async (comments = []) => {
    if (autoDraftRunningRef.current) {
      return;
    }

    const candidates = (Array.isArray(comments) ? comments : [])
      .filter((comment) => !comment?.isEngaged)
      .filter((comment) => {
        const commentId = String(comment?.id || '');
        if (!commentId) return false;
        if (generatedByCommentRef.current?.[commentId]) return false;
        if (toShortText(replyDraftByCommentRef.current?.[commentId] || '', 1200)) return false;
        return true;
      })
      .slice(0, AUTO_DRAFT_LIMIT);

    if (candidates.length === 0) {
      return;
    }

    autoDraftRunningRef.current = true;
    try {
      const runId = Date.now();
      autoDraftRunIdRef.current = runId;
      setAutoDraftProgress({
        running: true,
        completed: 0,
        total: candidates.length,
      });

      let completed = 0;
      const queue = [...candidates];
      const workers = Array.from({ length: Math.min(AUTO_DRAFT_CONCURRENCY, queue.length) }, async () => {
        while (queue.length > 0) {
          const comment = queue.shift();
          const commentId = String(comment?.id || '');
          if (!commentId) continue;
          try {
            setAiLoadingByComment((current) => ({ ...current, [commentId]: true }));
            const result = await generateForSingleComment(comment);
            const suggestions = parseSuggestionList(result);
            primeDraftFromSuggestions(commentId, suggestions, { overwrite: false });
          } catch {
            // Keep this silent to avoid toast spam during background draft preparation.
          } finally {
            setAiLoadingByComment((current) => ({ ...current, [commentId]: false }));
            completed += 1;
            if (autoDraftRunIdRef.current === runId) {
              setAutoDraftProgress({
                running: completed < candidates.length,
                completed,
                total: candidates.length,
              });
            }
          }
        }
      });

      await Promise.all(workers);
      if (autoDraftRunIdRef.current === runId) {
        setAutoDraftProgress((current) => ({
          ...current,
          running: false,
        }));
      }
    } finally {
      autoDraftRunningRef.current = false;
    }
  }, [generateForSingleComment, primeDraftFromSuggestions]);

  const handleAiAssist = useCallback(async (comment) => {
    const commentId = String(comment?.id || '');
    if (!commentId) return;

    try {
      setAiLoadingByComment((current) => ({ ...current, [commentId]: true }));
      const result = await generateForSingleComment(comment);
      const suggestions = parseSuggestionList(result);
      primeDraftFromSuggestions(commentId, suggestions, { overwrite: false });
      setExpandedCommentId(commentId);
      toast.success('AI suggestions ready');
    } catch (error) {
      toast.error(error?.response?.data?.error || 'Failed to generate reply suggestions');
    } finally {
      setAiLoadingByComment((current) => ({ ...current, [commentId]: false }));
    }
  }, [generateForSingleComment, primeDraftFromSuggestions]);

  const handleDraftChange = (commentId, value) => {
    const id = String(commentId || '');
    setReplyDraftByComment((current) => ({
      ...current,
      [id]: value,
    }));
  };

  const handleUseSuggestion = (commentId, value) => {
    const id = String(commentId || '');
    setReplyDraftByComment((current) => ({
      ...current,
      [id]: toShortText(value || '', 1200),
    }));
  };

  const handleSendReply = async (comment) => {
    const commentId = String(comment?.id || '');
    const replyText = toShortText(replyDraftByComment?.[commentId] || '', 1200);
    if (!replyText) {
      toast.error('No draft to approve yet. Click AI Assist to generate now.');
      return;
    }

    const generated = generatedByComment?.[commentId] || null;

    try {
      setSendingByComment((current) => ({ ...current, [commentId]: true }));
      const payload = {
        strategyId: selectedStrategyId || undefined,
        assistRequestId: generated?.requestId || undefined,
        postId: comment?.postId || undefined,
        linkedinPostId: comment?.linkedinPostId || undefined,
        sourceCommentId: comment?.sourceCommentId || undefined,
        commentText: comment?.commentText || '',
        replyText,
      };
      if (selectedAccountId) payload.accountId = selectedAccountId;
      if (selectedAccountType) payload.accountType = selectedAccountType;

      const response = await automationLinkedin.sendCommentReply(payload);
      const repliedAt = response?.data?.repliedAt || new Date().toISOString();

      setInboxComments((current) => current.map((item) => {
        if (String(item.id) !== commentId) return item;
        return {
          ...item,
          isEngaged: true,
          repliedAt,
          lastReplyText: replyText,
        };
      }));

      toast.success('Approved and posted to LinkedIn');
    } catch (error) {
      toast.error(error?.response?.data?.error || 'Failed to send reply');
    } finally {
      setSendingByComment((current) => ({ ...current, [commentId]: false }));
    }
  };

  const filteredComments = useMemo(() => {
    if (statusFilter === 'replied') {
      return inboxComments.filter((item) => Boolean(item?.isEngaged));
    }
    if (statusFilter === 'unreplied') {
      return inboxComments.filter((item) => !item?.isEngaged);
    }
    return inboxComments;
  }, [inboxComments, statusFilter]);

  const repliedCount = inboxComments.filter((item) => Boolean(item?.isEngaged)).length;
  const unrepliedCount = inboxComments.length - repliedCount;
  const adaptiveSummary = parseSummary(adaptiveRun);

  if (loading) {
    return (
      <div className="rounded-xl border border-gray-200 bg-white p-6 text-sm text-gray-600">
        Loading engagement assistant...
      </div>
    );
  }

  return (
    <div className="space-y-6 max-w-6xl mx-auto">
      <section className="rounded-2xl border border-cyan-100 bg-gradient-to-r from-cyan-50 to-blue-50 p-6">
        <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <h1 className="text-2xl font-bold text-gray-900 flex items-center gap-2">
              <MessageCircle className="w-6 h-6 text-cyan-600" />
              Engagement Assistant
            </h1>
            <p className="mt-2 text-sm text-gray-700">
              New comments get AI draft replies automatically. Review and approve to post.
            </p>
          </div>
          <div className="inline-flex items-center gap-2 rounded-full border border-cyan-200 bg-white px-3 py-1.5 text-xs font-medium text-cyan-700">
            <ShieldCheck className="h-3.5 w-3.5" />
            Approval-required publishing remains unchanged
          </div>
        </div>
      </section>

      <section className="rounded-xl border border-gray-200 bg-white p-5">
        <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <h2 className="text-lg font-semibold text-gray-900 flex items-center gap-2">
              <Brain className="w-5 h-5 text-indigo-600" />
              Adaptive Vault Loop (Optional)
            </h2>
            <p className="mt-1 text-sm text-gray-600">
              Use this when you want to refresh long-term learning across strategies.
            </p>
          </div>
          <div className="flex items-center gap-2">
            <span className="inline-flex rounded-full border border-gray-200 bg-gray-50 px-2.5 py-1 text-xs text-gray-700">
              Last run: {formatDateTime(adaptiveRun?.createdAt)}
            </span>
            <button
              type="button"
              onClick={() => setShowAdaptiveTools((prev) => !prev)}
              className="inline-flex items-center gap-2 rounded-lg border border-indigo-200 bg-indigo-50 px-3 py-2 text-sm font-medium text-indigo-700 hover:bg-indigo-100"
            >
              {showAdaptiveTools ? 'Hide learning tools' : 'Show learning tools'}
            </button>
          </div>
        </div>

        {showAdaptiveTools && (
          <div className="mt-4 space-y-4">
            <div className="flex items-center gap-2">
              <label className="inline-flex items-center gap-2 text-xs text-gray-600">
                <input
                  type="checkbox"
                  checked={includeContextRefresh}
                  onChange={(event) => setIncludeContextRefresh(event.target.checked)}
                  className="h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500"
                />
                Refresh context vaults
              </label>
              <button
                type="button"
                onClick={handleAdaptiveRun}
                disabled={runningAdaptive}
                className="inline-flex items-center gap-2 rounded-lg bg-indigo-600 px-3 py-2 text-sm font-medium text-white hover:bg-indigo-700 disabled:opacity-60"
              >
                <RefreshCw className={`h-4 w-4 ${runningAdaptive ? 'animate-spin' : ''}`} />
                {runningAdaptive ? 'Running...' : 'Run Adaptive Loop'}
              </button>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-4 gap-3 text-sm">
              <div className="rounded-lg border border-gray-200 p-3">
                <p className="text-xs text-gray-500 mb-1">Status</p>
                <p className="font-semibold text-gray-900">{adaptiveRun?.status || 'not_run'}</p>
              </div>
              <div className="rounded-lg border border-gray-200 p-3">
                <p className="text-xs text-gray-500 mb-1">Strategies scanned</p>
                <p className="font-semibold text-gray-900">{Number(adaptiveSummary?.strategy_count || 0)}</p>
              </div>
              <div className="rounded-lg border border-gray-200 p-3">
                <p className="text-xs text-gray-500 mb-1">Vault snapshots</p>
                <p className="font-semibold text-gray-900">{Number(adaptiveSummary?.vault_count || 0)}</p>
              </div>
              <div className="rounded-lg border border-gray-200 p-3">
                <p className="text-xs text-gray-500 mb-1">Last run</p>
                <p className="font-semibold text-gray-900">{formatDateTime(adaptiveRun?.createdAt)}</p>
              </div>
            </div>
          </div>
        )}
      </section>

      <section className="rounded-xl border border-gray-200 bg-white p-5">
        <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <h2 className="text-lg font-semibold text-gray-900 flex items-center gap-2">
              <Sparkles className="w-5 h-5 text-blue-600" />
              Comment Inbox
            </h2>
            <p className="mt-1 text-sm text-gray-600">
              Drafts are prepared for unreplied comments. Approve from this inbox to post.
            </p>
          </div>
          <div className="flex items-center gap-2">
            <select
              value={selectedStrategyId}
              onChange={(event) => setSelectedStrategyId(event.target.value)}
              className="rounded-lg border border-gray-300 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none"
            >
              <option value="">No strategy context</option>
              {strategyOptions.map((item) => (
                <option key={item.id} value={item.id}>
                  {toShortText(item.niche || 'Untitled strategy', 70)}
                </option>
              ))}
            </select>
            <select
              value={statusFilter}
              onChange={(event) => setStatusFilter(event.target.value)}
              className="rounded-lg border border-gray-300 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none"
            >
              <option value="unreplied">Unreplied</option>
              <option value="replied">Replied</option>
              <option value="all">All comments</option>
            </select>
            <button
              type="button"
              onClick={() => loadCommentInbox({ silent: false })}
              disabled={inboxLoading}
              className="inline-flex items-center gap-2 rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 disabled:opacity-60"
            >
              <RefreshCw className={`h-4 w-4 ${inboxLoading ? 'animate-spin' : ''}`} />
              Refresh
            </button>
          </div>
        </div>

        {inboxWarnings.length > 0 && (
          <div className="mt-3 rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-xs text-amber-800 space-y-1">
            {inboxWarnings.slice(0, 3).map((warning) => (
              <p key={warning}>{warning}</p>
            ))}
          </div>
        )}

        <div className="mt-3 flex flex-wrap items-center gap-2 text-xs">
          <span className="inline-flex rounded-full border border-emerald-200 bg-emerald-50 px-2.5 py-1 text-emerald-700">
            Unreplied: {unrepliedCount}
          </span>
          <span className="inline-flex rounded-full border border-gray-200 bg-gray-50 px-2.5 py-1 text-gray-700">
            Replied: {repliedCount}
          </span>
          <span className="text-gray-500">Loaded: {inboxComments.length}</span>
          {autoDraftProgress.running && (
            <span className="inline-flex rounded-full border border-blue-200 bg-blue-50 px-2.5 py-1 text-blue-700">
              Preparing drafts: {autoDraftProgress.completed}/{autoDraftProgress.total}
            </span>
          )}
        </div>

        {inboxLoading ? (
          <p className="mt-3 text-sm text-gray-600">Loading comment inbox...</p>
        ) : filteredComments.length === 0 ? (
          <p className="mt-3 text-sm text-gray-600">No comments in this filter right now.</p>
        ) : (
          <div className="mt-4 space-y-3">
            {filteredComments.map((comment) => {
              const commentId = String(comment.id);
              const generated = generatedByComment[commentId] || null;
              const suggestions = parseSuggestionList(generated);
              const isExpanded = expandedCommentId === commentId;
              const isAiLoading = Boolean(aiLoadingByComment[commentId]);
              const isSending = Boolean(sendingByComment[commentId]);
              const replyDraft = replyDraftByComment[commentId] || '';
              const hasKnownName = Boolean(toShortText(comment.commenterName, 80));
              const hasDraft = Boolean(toShortText(replyDraft, 1200));

              return (
                <div
                  key={comment.id}
                  className={`rounded-lg border p-3 ${comment.isEngaged ? 'border-gray-200 bg-white' : 'border-blue-200 bg-blue-50/30'}`}
                >
                  <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
                    <div className="flex flex-wrap items-center gap-2">
                      <span
                        className={`inline-flex rounded-full px-2 py-0.5 text-xs font-medium ${
                          comment.isEngaged
                            ? 'border border-gray-300 bg-gray-100 text-gray-700'
                            : 'border border-emerald-300 bg-emerald-100 text-emerald-800'
                        }`}
                      >
                        {comment.isEngaged ? 'Replied' : 'Unreplied'}
                      </span>
                      {!comment.isEngaged && hasDraft && (
                        <span className="inline-flex rounded-full border border-blue-200 bg-blue-100 px-2 py-0.5 text-xs font-medium text-blue-700">
                          Draft ready
                        </span>
                      )}
                      {hasKnownName && (
                        <span className="text-xs text-gray-600">{toShortText(comment.commenterName, 80)}</span>
                      )}
                    </div>

                    <div className="flex items-center gap-2 text-xs text-gray-600">
                      <span className="inline-flex items-center gap-1 rounded-full border border-gray-200 bg-white px-2 py-0.5">
                        <Clock3 className="h-3.5 w-3.5" />
                        {formatDateTime(comment.commentedAt || comment.postCreatedAt)}
                      </span>
                      <button
                        type="button"
                        onClick={() => setExpandedCommentId(isExpanded ? '' : commentId)}
                        className="inline-flex items-center gap-1 rounded-md border border-blue-200 bg-blue-100 px-2 py-1 text-xs font-medium text-blue-700 hover:bg-blue-200"
                      >
                        {isExpanded ? 'Hide' : (comment.isEngaged ? 'View' : 'Reply')}
                      </button>
                    </div>
                  </div>

                  <p className="mt-2 text-sm text-gray-900 whitespace-pre-wrap">{comment.commentText}</p>

                  <div className="mt-2 rounded-md border border-gray-200 bg-gray-50 p-2">
                    <p className="text-[11px] text-gray-500">Post context</p>
                    <p className="text-xs text-gray-700 whitespace-pre-wrap">{toShortText(comment.postSnippet, 260)}</p>
                    <p className="mt-1 text-[11px] text-gray-500">
                      Post comments: {Number(comment.postCommentCount || 0)}
                      {selectedStrategyLabel ? ` | Strategy: ${selectedStrategyLabel}` : ''}
                    </p>
                  </div>

                  {comment.isEngaged && !isExpanded && comment.lastReplyText && (
                    <p className="mt-2 text-xs text-gray-600">
                      Last reply: {toShortText(comment.lastReplyText, 180)}
                    </p>
                  )}

                  {isExpanded && (
                    <div className="mt-3 rounded-md border border-blue-200 bg-white p-3 space-y-3">
                      <textarea
                        value={replyDraft}
                        onChange={(event) => handleDraftChange(commentId, event.target.value)}
                        placeholder="AI draft appears here. Edit if needed before approval..."
                        rows={3}
                        className="w-full rounded-md border border-gray-300 px-3 py-2 text-sm focus:border-blue-500 focus:outline-none"
                      />

                      <div className="flex flex-wrap items-center gap-2">
                        <button
                          type="button"
                          onClick={() => handleAiAssist(comment)}
                          disabled={isAiLoading || isSending}
                          className="inline-flex items-center gap-1 rounded-md border border-blue-200 bg-blue-100 px-2.5 py-1.5 text-xs font-medium text-blue-700 hover:bg-blue-200 disabled:opacity-60"
                        >
                          <Sparkles className={`h-3.5 w-3.5 ${isAiLoading ? 'animate-pulse' : ''}`} />
                          {isAiLoading ? 'Generating...' : (suggestions.length > 0 ? 'Regenerate AI' : 'AI Assist')}
                        </button>
                        <button
                          type="button"
                          onClick={() => handleSendReply(comment)}
                          disabled={isAiLoading || isSending || !toShortText(replyDraft, 1200)}
                          className="inline-flex items-center gap-1 rounded-md bg-emerald-600 px-2.5 py-1.5 text-xs font-medium text-white hover:bg-emerald-700 disabled:opacity-60"
                        >
                          {isSending ? 'Approving...' : 'Approve & Send'}
                        </button>
                        {comment.isEngaged && (
                          <span className="text-[11px] text-gray-500">
                            Already engaged. Sending again will post another reply.
                          </span>
                        )}
                      </div>
                      {!comment.isEngaged && !hasDraft && !isAiLoading && (
                        <p className="text-[11px] text-gray-500">
                          Draft pending. Auto-generation runs after refresh, or click AI Assist now.
                        </p>
                      )}

                      {suggestions.length > 0 && (
                        <div className="rounded-md border border-blue-100 bg-blue-50/40 p-2 space-y-2">
                          <p className="text-xs font-medium text-blue-900">AI options</p>
                          {suggestions.map((item, index) => (
                            <div key={`${comment.id}-suggestion-${index}`} className="rounded-md border border-blue-100 bg-white p-2">
                              <p className="text-sm text-gray-800 whitespace-pre-wrap">{item.reply}</p>
                              <div className="mt-2 flex items-center gap-2">
                                <button
                                  type="button"
                                  onClick={() => handleUseSuggestion(commentId, item.reply)}
                                  className="inline-flex items-center gap-1 rounded-md border border-blue-200 px-2 py-1 text-xs font-medium text-blue-700 hover:bg-blue-50"
                                >
                                  Use
                                </button>
                                <button
                                  type="button"
                                  onClick={() => handleCopyReply(item.reply)}
                                  className="inline-flex items-center gap-1 rounded-md border border-blue-200 px-2 py-1 text-xs font-medium text-blue-700 hover:bg-blue-50"
                                >
                                  <Copy className="h-3.5 w-3.5" />
                                  Copy
                                </button>
                              </div>
                            </div>
                          ))}
                        </div>
                      )}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        )}
      </section>
    </div>
  );
}
